test

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,58 +1,58 @@
-name: "Terraform"
-on:
-  push:
-    branches:
-      - main
-    paths:
-      - terr/
-  pull_request:
-    branches:
-      - main
-    paths:
-      - terr/ 
+# name: "Terraform"
+# on:
+#   push:
+#     branches:
+#       - main
+#     paths:
+#       - terr/
+#   pull_request:
+#     branches:
+#       - main
+#     paths:
+#       - terr/ 
 
-env:
- AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
- AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
- BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
- AWS_REGION: us-east-1
+# env:
+#  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+#  AWS_REGION: us-east-1
 
-jobs: 
-  terraform:
-    name: "Apply terraform code changes"
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-        working-directory: ./terr
+# jobs: 
+#   terraform:
+#     name: "Apply terraform code changes"
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terr
     
-    steps:
-    - name: Checkout source core
-      uses: actions/checkout@v4
+#     steps:
+#     - name: Checkout source core
+#       uses: actions/checkout@v4
 
-    - name: Setup Terraform with specified version on the runner
-      uses: hashicorp/setup-terraform@v2
+#     - name: Setup Terraform with specified version on the runner
+#       uses: hashicorp/setup-terraform@v2
       
-    - name: Terraform init
-      id: init
-      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+#     - name: Terraform init
+#       id: init
+#       run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
 
-    - name: Terraform format
-      id: fmt
-      run: terraform fmt -check
+#     - name: Terraform format
+#       id: fmt
+#       run: terraform fmt -check
     
-    - name: Terraform Validate
-      id: validate
-      run: terraform validate -no-color
+#     - name: Terraform Validate
+#       id: validate
+#       run: terraform validate -no-color
 
-    - name: Terraform Plan
-      id: plan
-      run: terraform plan -no-color -input=false -out planfile
-      continue-on-error: true
+#     - name: Terraform Plan
+#       id: plan
+#       run: terraform plan -no-color -input=false -out planfile
+#       continue-on-error: true
 
-    - name: Terraform plan status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     - name: Terraform plan status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
 
      
 
